[build]
  publish = "."

[build.environment]
  NODE_ENV = "production"

# Basic headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# SPA redirect - but don't redirect function calls
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions directory
[functions]
  directory = "functions/"

# Environment variables for different contexts
[context.production.environment]
  NODE_ENV = "production"
  DATABASE_URL = "postgresql://972cfe%40gmail.com:Canada%402024%21CFEli@ep-rough-sea-a5xdeng4.us-east-2.aws.neon.tech/neondb?sslmode=require"
  JWT_SECRET = "hr-system-jwt-secret-key-2024-secure-token"
  SESSION_TIMEOUT_HOURS = "8"
  ENABLE_AUDIT_LOGS = "true"
  MAX_FILE_SIZE_MB = "25"
  COMPANY_NAME = "החברה שלנו"
  DEFAULT_LANGUAGE = "he"
  SUPPORT_EMAIL = "support@company.com"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
  DATABASE_URL = "postgresql://972cfe%40gmail.com:Canada%402024%21CFEli@ep-rough-sea-a5xdeng4.us-east-2.aws.neon.tech/neondb?sslmode=require"
  JWT_SECRET = "hr-system-jwt-secret-key-2024-secure-token"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  DATABASE_URL = "postgresql://972cfe%40gmail.com:Canada%402024%21CFEli@ep-rough-sea-a5xdeng4.us-east-2.aws.neon.tech/neondb?sslmode=require"
  JWT_SECRET = "hr-system-jwt-secret-key-2024-secure-token"