[build]
  publish = "."

[build.environment]
  NODE_ENV = "production"

# Basic headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions directory (for future serverless functions)
[functions]
  directory = "functions/"

# Environment variables will be added based on specifications
[context.production.environment]
  NODE_ENV = "production"